/**
 * Sample Founder Codex — Linear.
 *
 * The brand-level language constants any AI writing assistant should
 * load before drafting copy for this brand. Single source of truth for
 * the seven language axes, the canonical voice paragraph, and the
 * register constraints that distinguish Linear's copy from generic SaaS
 * marketing.
 *
 * Generated by the WhyStrohm scanner against https://linear.app/ on
 * 2026-05-18 and verified against three failing-quote violations
 * extracted from the live site at scan time (see ./examples/bad-post.md
 * for the slop pattern, ./examples/good-post.md for the target voice).
 *
 * Sister files: ./codex.rules.json, ./forbidden.json, ./CLAUDE.md.
 */

export interface CodexAxis {
  readonly name: string;
  readonly score: number;
  readonly note: string;
}

export interface BrandCodex {
  readonly brand: string;
  readonly website: string;
  readonly voiceParagraph: string;
  readonly axes: readonly CodexAxis[];
  readonly registerConstraints: readonly string[];
  readonly approvedPatterns: readonly string[];
}

export const codex: BrandCodex = {
  brand: "Linear",
  website: "https://linear.app/",

  voiceParagraph:
    "Linear's language is spare, precise, and built around momentum. Short declarative phrases over explanatory prose. Product specifics do the persuasion. The brand sounds like a senior engineer who also runs the company, not a SaaS marketing team.",

  axes: [
    {
      name: "Authority",
      score: 8,
      note: "Strong product credibility. Lean on shipped features and engineering specifics, not abstract claims.",
    },
    {
      name: "Directness",
      score: 7,
      note: "Headlines are tight. Body copy should match. No throat-clearing, no AI-era hedges.",
    },
    {
      name: "Concrete Specificity",
      score: 6,
      note: "Replace abstract noun clusters with named systems, named decisions, or named numbers.",
    },
    {
      name: "Founder Presence",
      score: 4,
      note: "First person plural is fine. First person singular from the founder is rare and earned.",
    },
    {
      name: "Technical Density",
      score: 7,
      note: "Comfortable with PRDs, PRs, GraphQL references without over-explaining. Don't dumb things down for engineering audiences.",
    },
    {
      name: "Emotional Temperature",
      score: 3,
      note: "Cool and controlled by design. Avoid enthusiasm verbs (thrilled, excited, delighted).",
    },
    {
      name: "Vulnerability",
      score: 2,
      note: "Process and uncertainty are rarely surfaced. When they are, it's a deliberate choice — not the default.",
    },
  ],

  registerConstraints: [
    "Median sentence length under 20 words.",
    "No em-dashes. Use periods, commas, or colons.",
    "No enthusiasm verbs (thrilled, excited, delighted, proud).",
    "Concrete subjects over abstract noun phrases.",
    "Product specifics (Linear Cycles, Linear Roadmap, GraphQL API) over generic 'platform' / 'solution' / 'experience' language.",
    "Numbers stated bare — '25,000 companies' not 'thousands of companies' or 'rapidly growing user base'.",
  ],

  approvedPatterns: [
    "Subject + active verb + concrete object.",
    "Claim followed immediately by proof (named decision, named number, or named system).",
    "Tight juxtaposition: the old way / the new way. One sentence each.",
    "Founder voice — when used — references a specific team decision, not a vision.",
  ],
} as const;
